import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { ApiError, useAuth } from "./auth";
import type { OnboardingStatus } from "./api";

type Intake = { career_direction: string; work_preferences: string[]; constraints: string[]; self_assessment: string[]; motivations: string[]; tradeoffs: string[]; eligibility: { work_authorisation: string[]; security_clearances: string[]; locations: string[] } };
type Insight = { text: string; source_references: Array<{ source_type: string; reference: string }> };
type Assessment = { status: "review_ready" | "confirmed" | "stale"; content: { professional_positioning: Insight; transferable_strengths: Insight[]; development_gaps: Insight[]; role_hypotheses: Insight[]; transition_assessment: Insight; open_questions: Insight[]; career_strategy_summary: Insight; job_search_strategy_summary: Insight } };
type Clarification = { clarification_id: string; question_text: string; priority_index: number; status: "unanswered" | "review_ready" | "confirmed"; answer_text: string | null; interpretation: { answer_kind: string; confirmed_context_summary: string; proposed_evidence: Array<{ title: string; text: string; skills: string[] }> } | null };
type IntakeRead = Intake & { updated_at?: string };
const blank = (): Intake => ({ career_direction: "", work_preferences: [], constraints: [], self_assessment: [], motivations: [], tradeoffs: [], eligibility: { work_authorisation: [], security_clearances: [], locations: [] } });
const intakeLists = ["work_preferences", "constraints", "self_assessment", "motivations", "tradeoffs"] as const;
const eligibilityLists = ["work_authorisation", "security_clearances", "locations"] as const;
const friendly = () => "This Adviser state changed or is unavailable. Refresh and try again.";
const sourceLabel = (source: string) => source === "intake" ? "Based on your adviser intake" : source === "clarification" ? "Based on a confirmed clarification" : "Based on confirmed career evidence";

function ListInput({ label, values, onChange }: { label: string; values: string[]; onChange: (next: string[]) => void }) {
  return <fieldset className="adviser-list"><legend>{label}</legend>{values.map((value, index) => <div className="inline-control" key={index}><input aria-label={`${label} ${index + 1}`} value={value} onChange={(event) => onChange(values.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} /><button type="button" className="button-secondary" onClick={() => onChange(values.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></div>)}<button type="button" className="button-secondary" onClick={() => onChange([...values, ""])}>Add</button></fieldset>;
}

function AssessmentView({ assessment }: { assessment: Assessment }) {
  const sections: Array<[string, Insight[]]> = [["Professional positioning", [assessment.content.professional_positioning]], ["Transferable strengths", assessment.content.transferable_strengths], ["Development gaps", assessment.content.development_gaps], ["Role hypotheses", assessment.content.role_hypotheses], ["Transition assessment", [assessment.content.transition_assessment]], ["Open questions", assessment.content.open_questions], ["Career strategy summary", [assessment.content.career_strategy_summary]], ["Job-search strategy summary", [assessment.content.job_search_strategy_summary]]];
  return <section className="card adviser-assessment"><h2>{assessment.status === "stale" ? "Adviser assessment needs reassessment" : "Career Adviser assessment"}</h2>{sections.map(([title, insights]) => <section className="cv-section" key={title}><h3>{title}</h3>{insights.map((insight, index) => <article key={index}><p>{insight.text}</p><p className="muted">{[...new Set(insight.source_references.map((reference) => sourceLabel(reference.source_type)))].join(" · ")}</p></article>)}</section>)}</section>;
}

export function AdviserPage() {
  const { api } = useAuth(); const [onboarding, setOnboarding] = useState<OnboardingStatus | undefined>(); const [saved, setSaved] = useState<Intake | null | undefined>(undefined); const [form, setForm] = useState<Intake>(blank()); const [assessment, setAssessment] = useState<Assessment | null | undefined>(undefined); const [clarifications, setClarifications] = useState<Clarification[]>([]); const [active, setActive] = useState<string | null>(null); const [answer, setAnswer] = useState(""); const [interpretedAnswer, setInterpretedAnswer] = useState(""); const [confirmedTransition, setConfirmedTransition] = useState<Clarification | null>(null); const [pending, setPending] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const generation = useRef(0);
  const normalize = (value: IntakeRead): Intake => ({ career_direction: value.career_direction, work_preferences: value.work_preferences, constraints: value.constraints, self_assessment: value.self_assessment, motivations: value.motivations, tradeoffs: value.tradeoffs, eligibility: value.eligibility });
  const resetClarifications = () => { setClarifications([]); setActive(null); setAnswer(""); setInterpretedAnswer(""); };
  const dirty = saved === undefined ? false : JSON.stringify(saved ?? blank()) !== JSON.stringify(form); const locked = Boolean(pending) || dirty || saved === undefined || saved === null;
  const load = async () => { const request = ++generation.current; setError(""); setSaved(undefined); setAssessment(undefined); resetClarifications(); try { const status = await api.request<OnboardingStatus>("/api/v1/onboarding/status"); if (request !== generation.current) return; setOnboarding(status); if (!status.candidate_context_ready) return; try { const intake = normalize(await api.request<IntakeRead>("/api/v1/candidate-adviser/intake")); if (request === generation.current) { setSaved(intake); setForm(intake); } } catch (caught) { if (request !== generation.current) return; if (caught instanceof ApiError && caught.status === 404) { setSaved(null); setForm(blank()); } else { setSaved(undefined); setError("Adviser intake is unavailable."); return; } } await loadAssessment(request); } catch { if (request === generation.current) setError("Adviser status is unavailable."); } };
  const loadAssessment = async (request = ++generation.current) => { setAssessment(undefined); resetClarifications(); try { const found = await api.request<Assessment>("/api/v1/candidate-adviser/assessment"); if (request !== generation.current) return; setAssessment(found); if (found.status === "confirmed") await loadClarifications(request); } catch (caught) { if (request !== generation.current) return; if (caught instanceof ApiError && caught.status === 404) setAssessment(null); else { setAssessment(undefined); setError("Adviser assessment is unavailable."); } } };
  const loadClarifications = async (request = ++generation.current) => { resetClarifications(); try { const found = await api.request<Clarification[]>("/api/v1/candidate-adviser/clarifications"); if (request !== generation.current) return; const sorted = [...found].sort((a,b) => a.priority_index - b.priority_index || a.clarification_id.localeCompare(b.clarification_id)); setClarifications(sorted); const reviewing = sorted.filter((item) => item.status === "review_ready")[0]; if (reviewing) { setActive(reviewing.clarification_id); setAnswer(reviewing.answer_text ?? ""); setInterpretedAnswer(reviewing.answer_text ?? ""); } } catch { if (request === generation.current) setError("Clarifications are unavailable."); } };
  // Intake PUT and lifecycle conflict recovery already have a known-good
  // intake baseline. Invalidate old dependent authority immediately and load
  // status/assessment independently: an onboarding outage must not leave an
  // old confirmed assessment actionable.
  const refreshDependentAuthority = async () => {
    const request = ++generation.current; setError(""); setAssessment(undefined); resetClarifications();
    const [statusResult, assessmentResult] = await Promise.allSettled([
      api.request<OnboardingStatus>("/api/v1/onboarding/status"),
      api.request<Assessment>("/api/v1/candidate-adviser/assessment"),
    ]);
    if (request !== generation.current) return;
    if (statusResult.status === "fulfilled") setOnboarding(statusResult.value);
    else setError("Adviser status is unavailable.");
    if (assessmentResult.status === "fulfilled") {
      setAssessment(assessmentResult.value);
      if (assessmentResult.value.status !== "stale") setConfirmedTransition(null);
      if (assessmentResult.value.status === "confirmed") await loadClarifications(request);
      return;
    }
    const caught = assessmentResult.reason;
    if (caught instanceof ApiError && caught.status === 404) { setAssessment(null); setConfirmedTransition(null); }
    else { setAssessment(undefined); setError("Adviser assessment is unavailable."); }
  };
  useEffect(() => { void load(); }, []);
  const save = async () => { if (pending || saved === undefined) return; setPending("save"); try { const found = normalize(await api.request<IntakeRead>("/api/v1/candidate-adviser/intake", { method: "PUT", body: JSON.stringify(form) })); setNotice(""); setSaved(found); setForm(found); resetClarifications(); await refreshDependentAuthority(); } catch { setError("Adviser intake could not be saved."); } finally { setPending(""); } };
  const mutateAssessment = async () => { if (locked || pending) return; setPending("assessment"); try { const found = await api.request<Assessment>("/api/v1/candidate-adviser/assessment", { method: "POST" }); setNotice(""); setConfirmedTransition(null); setAssessment(found); resetClarifications(); } catch (caught) { setError(caught instanceof ApiError && (caught.status === 502 || caught.status === 503) ? "Assessment generation is temporarily unavailable." : friendly()); if (caught instanceof ApiError && caught.status === 409) { setNotice("Adviser state changed. The current state has been refreshed."); await refreshDependentAuthority(); } } finally { setPending(""); } };
  const confirmAssessment = async () => { if (locked || pending) return; setPending("confirm-assessment"); try { await api.request<Assessment>("/api/v1/candidate-adviser/assessment/confirm", { method: "POST" }); setNotice(""); await refreshDependentAuthority(); } catch (caught) { setError(caught instanceof ApiError && (caught.status === 502 || caught.status === 503) ? "Assessment confirmation is temporarily unavailable." : friendly()); if (caught instanceof ApiError && caught.status === 409) { setNotice("Adviser state changed. The current state has been refreshed."); await refreshDependentAuthority(); } } finally { setPending(""); } };
  const interpret = async () => { if (!active || locked) return; setPending("interpret"); try { const found = await api.request<Clarification>(`/api/v1/candidate-adviser/clarifications/${active}/answer`, { method: "POST", body: JSON.stringify({ answer_text: answer }) }); setNotice(""); setClarifications((items) => items.map((item) => item.clarification_id === found.clarification_id ? found : item)); setAnswer(found.answer_text ?? ""); setInterpretedAnswer(found.answer_text ?? ""); } catch (caught) { if (caught instanceof ApiError && (caught.status === 404 || caught.status === 409)) { resetClarifications(); setNotice("Adviser state changed. The current state has been refreshed."); await refreshDependentAuthority(); } else setError(caught instanceof ApiError && (caught.status === 502 || caught.status === 503) ? "Clarification interpretation is temporarily unavailable." : friendly()); } finally { setPending(""); } };
  const confirmClarification = async () => { if (!active || locked || answer !== interpretedAnswer) return; setPending("confirm-clarification"); try { const found = await api.request<Clarification>(`/api/v1/candidate-adviser/clarifications/${active}/confirm`, { method: "POST" }); setNotice(""); generation.current += 1; resetClarifications(); setConfirmedTransition(found); await refreshDependentAuthority(); } catch (caught) { if (caught instanceof ApiError && (caught.status === 404 || caught.status === 409)) { resetClarifications(); setNotice("Adviser state changed. The current state has been refreshed."); await refreshDependentAuthority(); } else setError(caught instanceof ApiError && (caught.status === 502 || caught.status === 503) ? "Clarification confirmation is temporarily unavailable." : friendly()); } finally { setPending(""); } };
  if (onboarding === undefined) return <main className="workspace adviser-page"><p className="muted">Loading Career Adviser…</p>{error && <><p role="alert">{error}</p><button onClick={() => void load()}>Retry</button></>}</main>;
  if (!onboarding.candidate_context_ready) return <main className="workspace adviser-page"><section className="card"><h1>Complete your CV first</h1><p>Your confirmed CV creates the core candidate context used by Career Adviser.</p><Link to="/cv">Go to CV onboarding</Link></section></main>;
  const current = clarifications.find((item) => item.clarification_id === active); const canConfirm = current?.status === "review_ready" && answer === interpretedAnswer && !locked;
  return <main className="workspace adviser-page">{error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}{saved === undefined ? <section className="card"><h1>Career Adviser</h1><p className="muted">Loading Adviser intake…</p><button onClick={() => void load()}>Retry</button></section> : <><section className="card adviser-intake"><h1>Career Adviser</h1><p className="muted">Career Adviser is optional enrichment for your confirmed candidate context.</p>{dirty && <p className="notice">Unsaved intake changes</p>}<label>Career direction<textarea value={form.career_direction} onChange={(event) => setForm({ ...form, career_direction: event.target.value })} /></label>{intakeLists.map((key) => <ListInput key={key} label={key.replaceAll("_", " ")} values={form[key]} onChange={(next) => setForm({ ...form, [key]: next })} />)}{eligibilityLists.map((key) => <ListInput key={key} label={key.replaceAll("_", " ")} values={form.eligibility[key]} onChange={(next) => setForm({ ...form, eligibility: { ...form.eligibility, [key]: next } })} />)}<div className="cv-actions"><button disabled={Boolean(pending)} onClick={() => void save()}>Save intake</button>{dirty && <button className="button-secondary" disabled={Boolean(pending)} onClick={() => setForm(saved ?? blank())}>Discard changes</button>}</div></section>
    {assessment && <AssessmentView assessment={assessment} />}
    <section className="card"><h2>Assessment lifecycle</h2>{assessment === undefined ? <><p className="muted">Loading assessment…</p><button onClick={() => void load()}>Retry</button></> : !assessment && <button disabled={locked} onClick={() => void mutateAssessment()}>Generate assessment</button>}{assessment?.status === "review_ready" && <p className="notice">Assessment ready for your review.</p>}{assessment?.status === "confirmed" && <p className="notice">Assessment is current.</p>}{assessment?.status === "review_ready" && <div className="cv-actions"><button disabled={locked} onClick={() => void confirmAssessment()}>Confirm assessment</button><button className="button-secondary" disabled={locked} onClick={() => void mutateAssessment()}>Regenerate assessment</button></div>}{assessment?.status === "stale" && <button disabled={locked} onClick={() => void mutateAssessment()}>Reassess</button>}</section>
    {confirmedTransition && <section className="card"><h2>Clarification confirmed</h2><p>{confirmedTransition.question_text}</p>{confirmedTransition.answer_text && <p><strong>Answer:</strong> {confirmedTransition.answer_text}</p>}{confirmedTransition.interpretation && <article className="evidence-card"><p><strong>{confirmedTransition.interpretation.answer_kind.replaceAll("_", " ")}</strong></p><p>{confirmedTransition.interpretation.confirmed_context_summary}</p>{confirmedTransition.interpretation.proposed_evidence.map((item, index) => <p key={index}>{item.title}: {item.text}</p>)}</article>}<p className="muted">This confirmed clarification is now read-only. Reassess to use it in a new adviser assessment.</p></section>}
    {assessment?.status === "confirmed" && <section className="card"><h2>Current clarification</h2><p className="muted">Confirmed clarifications: {onboarding.adviser.confirmed_clarification_count}</p>{clarifications.length === 0 ? <p> No current clarification questions. Adviser enrichment is current.</p> : clarifications.map((item) => <article className="clarification-card" key={item.clarification_id}><p>{item.question_text}</p><button className="button-secondary" disabled={locked || (current?.status === "review_ready" && active !== item.clarification_id)} onClick={() => { setActive(item.clarification_id); setAnswer(item.answer_text ?? ""); setInterpretedAnswer(item.status === "review_ready" ? item.answer_text ?? "" : ""); }}>Work on this question</button></article>)}{current && <section className="cv-section"><h3>Answer</h3><label htmlFor="clarification-answer">Clarification answer</label><textarea id="clarification-answer" value={answer} onChange={(event) => setAnswer(event.target.value)} disabled={locked} />{current.interpretation && <article className="evidence-card"><p><strong>{current.interpretation.answer_kind.replaceAll("_", " ")}</strong></p><p>{current.interpretation.confirmed_context_summary}</p>{current.interpretation.proposed_evidence.map((item, index) => <p key={index}>{item.title}: {item.text}</p>)}{answer !== interpretedAnswer && <p className="notice">Answer changed — re-interpret before confirmation.</p>}</article>}<div className="cv-actions"><button disabled={locked || !answer.trim()} onClick={() => void interpret()}>{current.status === "review_ready" ? "Re-interpret answer" : "Interpret answer"}</button><button disabled={!canConfirm} onClick={() => void confirmClarification()}>Confirm clarification</button></div></section>}</section>}
  </>}</main>;
}
