import { useEffect, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ApiError, useAuth } from "./auth";
import type { OnboardingStatus } from "./api";
import { ProfileSuggestions } from "./ProfileSuggestions";

type Intake = { career_direction: string; work_preferences: string[]; constraints: string[]; self_assessment: string[]; motivations: string[]; tradeoffs: string[]; eligibility: { work_authorisation: string[]; security_clearances: string[]; locations: string[] } };
type Insight = { text: string; source_references: Array<{ source_type: string; reference: string }> };
type Assessment = { status: "review_ready" | "confirmed" | "stale"; content: { professional_positioning: Insight; transferable_strengths: Insight[]; development_gaps: Insight[]; role_hypotheses: Insight[]; transition_assessment: Insight; open_questions: Insight[]; career_strategy_summary: Insight; job_search_strategy_summary: Insight } };
type Clarification = { clarification_id: string; question_text: string; priority_index: number; status: "unanswered" | "review_ready" | "confirmed"; answer_text: string | null; interpretation: { answer_kind: "career_fact" | "mixed" | "eligibility_fact" | "preference_intent" | "insufficient"; confirmed_context_summary: string; proposed_evidence: Array<{ title: string; text: string; skills: string[] }> } | null };
type IntakeRead = Intake & { updated_at?: string };
type Journey = NonNullable<OnboardingStatus["adviser"]["journey"]>;
type Enrichment = Journey["next_enrichment"];
const blank = (): Intake => ({ career_direction: "", work_preferences: [], constraints: [], self_assessment: [], motivations: [], tradeoffs: [], eligibility: { work_authorisation: [], security_clearances: [], locations: [] } });
const intakeLists = ["work_preferences", "constraints", "self_assessment", "motivations", "tradeoffs"] as const;
const eligibilityLists = ["work_authorisation", "security_clearances", "locations"] as const;
const friendly = () => "This Adviser state changed or is unavailable. Refresh and try again.";
const sourceLabel = (source: string) => source === "intake" ? "Based on your adviser intake" : source === "clarification" ? "Based on a confirmed clarification" : "Based on confirmed career evidence";

function ListInput({ label, values, onChange, disabled }: { label: string; values: string[]; onChange: (next: string[]) => void; disabled: boolean }) {
  return <fieldset className="adviser-list"><legend>{label}</legend>{values.map((value, index) => <div className="inline-control" key={index}><input aria-label={`${label} ${index + 1}`} value={value} disabled={disabled} onChange={(event) => onChange(values.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} /><button type="button" className="button-secondary" disabled={disabled} onClick={() => onChange(values.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></div>)}<button type="button" className="button-secondary" disabled={disabled} onClick={() => onChange([...values, ""])}>Add</button></fieldset>;
}

function AssessmentView({ assessment }: { assessment: Assessment }) {
  const sections: Array<[string, Insight[]]> = [["Professional positioning", [assessment.content.professional_positioning]], ["Transferable strengths", assessment.content.transferable_strengths], ["Development gaps", assessment.content.development_gaps], ["Role hypotheses", assessment.content.role_hypotheses], ["Transition assessment", [assessment.content.transition_assessment]], ["Open questions", assessment.content.open_questions], ["Career strategy summary", [assessment.content.career_strategy_summary]], ["Job-search strategy summary", [assessment.content.job_search_strategy_summary]]];
  return <section className="card adviser-assessment"><h2>Career assessment</h2><div className="adviser-assessment-summary" aria-label="Assessment summary"><section><h3>How you’re positioned</h3><p>{assessment.content.professional_positioning.text}</p></section>{assessment.content.role_hypotheses.length > 0 && <section><h3>Directions to explore</h3><ul>{assessment.content.role_hypotheses.slice(0, 3).map((item, index) => <li key={index}>{item.text}</li>)}</ul></section>}{assessment.content.transferable_strengths.length > 0 && <section><h3>Your strongest advantages</h3><ul>{assessment.content.transferable_strengths.slice(0, 3).map((item, index) => <li key={index}>{item.text}</li>)}</ul></section>}{assessment.content.development_gaps.length > 0 && <section><h3>Areas to build</h3><ul>{assessment.content.development_gaps.slice(0, 3).map((item, index) => <li key={index}>{item.text}</li>)}</ul></section>}</div><details className="adviser-assessment-details"><summary>Read full assessment and sources</summary>{sections.map(([title, insights]) => <section className="cv-section" key={title}><h3>{title}</h3>{insights.map((insight, index) => <article key={index}><p>{insight.text}</p><p className="muted">{[...new Set(insight.source_references.map((reference) => sourceLabel(reference.source_type)))].join(" · ")}</p></article>)}</section>)}</details></section>;
}

export function AdviserPage() {
  const { api } = useAuth(); const navigate = useNavigate(); const [onboarding, setOnboarding] = useState<OnboardingStatus | undefined>(); const [saved, setSaved] = useState<Intake | null | undefined>(undefined); const [form, setForm] = useState<Intake>(blank()); const [assessment, setAssessment] = useState<Assessment | null | undefined>(undefined); const [clarifications, setClarifications] = useState<Clarification[]>([]); const [clarificationAuthority, setClarificationAuthority] = useState<"idle" | "loading" | "ready" | "unavailable">("idle"); const [clarificationError, setClarificationError] = useState(""); const [active, setActive] = useState<string | null>(null); const [answer, setAnswer] = useState(""); const [interpretedAnswer, setInterpretedAnswer] = useState(""); const [confirmedTransition, setConfirmedTransition] = useState<Clarification | null>(null); const [followUpDismissed, setFollowUpDismissed] = useState(false); const [pending, setPending] = useState(""); const [intakeRefreshPending, setIntakeRefreshPending] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const generation = useRef(0); const answerRef = useRef<HTMLTextAreaElement>(null);
  const normalize = (value: IntakeRead): Intake => ({ career_direction: value.career_direction, work_preferences: value.work_preferences, constraints: value.constraints, self_assessment: value.self_assessment, motivations: value.motivations, tradeoffs: value.tradeoffs, eligibility: value.eligibility });
  const resetClarifications = (authority: "idle" | "loading" | "ready" | "unavailable" = "idle") => { setClarifications([]); setClarificationAuthority(authority); setActive(null); setAnswer(""); setInterpretedAnswer(""); };
  const dirty = saved === undefined ? false : JSON.stringify(saved ?? blank()) !== JSON.stringify(form); const locked = Boolean(pending) || dirty || saved === undefined || saved === null;
  const load = async () => { const request = ++generation.current; setError(""); setSaved(undefined); setAssessment(undefined); resetClarifications(); try { const status = await api.request<OnboardingStatus>("/api/v1/onboarding/status"); if (request !== generation.current) return; setOnboarding(status); if (!status.candidate_context_ready) return; try { const intake = normalize(await api.request<IntakeRead>("/api/v1/candidate-adviser/intake")); if (request === generation.current) { setSaved(intake); setForm(intake); } } catch (caught) { if (request !== generation.current) return; if (caught instanceof ApiError && caught.status === 404) { setSaved(null); setForm(blank()); } else { setSaved(undefined); setError("Adviser intake is unavailable."); return; } } await loadAssessment(request); } catch { if (request === generation.current) setError("Adviser status is unavailable."); } };
  const loadAssessment = async (request = ++generation.current) => { setAssessment(undefined); resetClarifications(); try { const found = await api.request<Assessment>("/api/v1/candidate-adviser/assessment"); if (request !== generation.current) return; setAssessment(found); if (found.status === "confirmed") await loadClarifications(request); } catch (caught) { if (request !== generation.current) return; if (caught instanceof ApiError && caught.status === 404) setAssessment(null); else { setAssessment(undefined); setError("Adviser assessment is unavailable."); } } };
  const loadClarifications = async (request = ++generation.current) => { resetClarifications("loading"); setClarificationError(""); try { const found = await api.request<Clarification[]>("/api/v1/candidate-adviser/clarifications"); if (request !== generation.current) return; const sorted = [...found].sort((a,b) => a.priority_index - b.priority_index || a.clarification_id.localeCompare(b.clarification_id)); setClarifications(sorted); setClarificationAuthority("ready"); setFollowUpDismissed(false); const currentQuestion = sorted.find((item) => item.status === "review_ready") ?? sorted[0]; if (currentQuestion) { setActive(currentQuestion.clarification_id); setAnswer(currentQuestion.answer_text ?? ""); setInterpretedAnswer(currentQuestion.status === "review_ready" ? currentQuestion.answer_text ?? "" : ""); } } catch { if (request === generation.current) { resetClarifications("unavailable"); setClarificationError("Your optional follow-up is unavailable right now."); } } };
  // Intake PUT and lifecycle conflict recovery already have a known-good
  // intake baseline. Invalidate old dependent authority immediately and load
  // status/assessment independently: an onboarding outage must not leave an
  // old confirmed assessment actionable.
  const refreshDependentAuthority = async () => {
    const request = ++generation.current; setError(""); setAssessment(undefined); resetClarifications();
    const [statusResult, assessmentResult] = await Promise.allSettled([
      api.request<OnboardingStatus>("/api/v1/onboarding/status"),
      api.request<Assessment>("/api/v1/candidate-adviser/assessment"),
    ]);
    if (request !== generation.current) return;
    if (statusResult.status === "fulfilled") setOnboarding(statusResult.value);
    else setError("Adviser status is unavailable.");
    if (assessmentResult.status === "fulfilled") {
      setAssessment(assessmentResult.value);
      if (assessmentResult.value.status !== "stale") setConfirmedTransition(null);
      if (assessmentResult.value.status === "confirmed") await loadClarifications(request);
      return;
    }
    const caught = assessmentResult.reason;
    if (caught instanceof ApiError && caught.status === 404) { setAssessment(null); setConfirmedTransition(null); }
    else { setAssessment(undefined); setError("Adviser assessment is unavailable."); }
  };
  useEffect(() => { void load(); }, []);
  const save = async () => { if (pending || saved === undefined) return; setPending("save"); setIntakeRefreshPending(false); setError(""); setNotice(""); try { const found = normalize(await api.request<IntakeRead>("/api/v1/candidate-adviser/intake", { method: "PUT", body: JSON.stringify(form) })); setSaved(found); setForm(found); setNotice("Adviser intake saved."); resetClarifications(); setIntakeRefreshPending(true); await refreshDependentAuthority(); } catch { setError("Adviser intake could not be saved."); } finally { setIntakeRefreshPending(false); setPending(""); } };
  const mutateAssessment = async () => { if (locked || pending) return; setPending("assessment"); setError(""); setNotice(""); try { const found = await api.request<Assessment>("/api/v1/candidate-adviser/assessment", { method: "POST" }); setConfirmedTransition(null); setAssessment(found); resetClarifications(); } catch (caught) { setError(caught instanceof ApiError && (caught.status === 502 || caught.status === 503) ? "Assessment generation is temporarily unavailable." : friendly()); if (caught instanceof ApiError && caught.status === 409) { setNotice("Adviser state changed. The current state has been refreshed."); await refreshDependentAuthority(); } } finally { setPending(""); } };
  const confirmAssessment = async () => { if (locked || pending) return; setPending("confirm-assessment"); setError(""); setNotice(""); try { await api.request<Assessment>("/api/v1/candidate-adviser/assessment/confirm", { method: "POST" }); await refreshDependentAuthority(); } catch (caught) { setError(caught instanceof ApiError && (caught.status === 502 || caught.status === 503) ? "Assessment confirmation is temporarily unavailable." : friendly()); if (caught instanceof ApiError && caught.status === 409) { setNotice("Adviser state changed. The current state has been refreshed."); await refreshDependentAuthority(); } } finally { setPending(""); } };
  const interpret = async () => { if (!active || locked) return; setPending("interpret"); setError(""); setNotice(""); try { const found = await api.request<Clarification>(`/api/v1/candidate-adviser/clarifications/${active}/answer`, { method: "POST", body: JSON.stringify({ answer_text: answer }) }); setClarifications((items) => items.map((item) => item.clarification_id === found.clarification_id ? found : item)); setAnswer(found.answer_text ?? ""); setInterpretedAnswer(found.answer_text ?? ""); } catch (caught) { if (caught instanceof ApiError && (caught.status === 404 || caught.status === 409)) { resetClarifications(); setNotice("Adviser state changed. The current state has been refreshed."); await refreshDependentAuthority(); } else setError(caught instanceof ApiError && (caught.status === 502 || caught.status === 503) ? "Clarification interpretation is temporarily unavailable." : friendly()); } finally { setPending(""); } };
  const confirmClarification = async () => { if (!active || locked || answer !== interpretedAnswer) return; setPending("confirm-clarification"); setError(""); setNotice(""); try { const found = await api.request<Clarification>(`/api/v1/candidate-adviser/clarifications/${active}/confirm`, { method: "POST" }); generation.current += 1; resetClarifications(); setConfirmedTransition(found); await refreshDependentAuthority(); } catch (caught) { if (caught instanceof ApiError && (caught.status === 404 || caught.status === 409)) { resetClarifications(); setNotice("Adviser state changed. The current state has been refreshed."); await refreshDependentAuthority(); } else setError(caught instanceof ApiError && (caught.status === 502 || caught.status === 503) ? "Clarification confirmation is temporarily unavailable." : friendly()); } finally { setPending(""); } };
  if (onboarding === undefined) return <main className="workspace adviser-page"><p className="muted" role="status">Loading Career Adviser…</p>{error && <><p role="alert">{error}</p><button onClick={() => void load()}>Retry</button></>}</main>;
  if (!onboarding.candidate_context_ready) return <main className="workspace adviser-page"><section className="card"><h1>Set up Career Adviser</h1><p>Your confirmed CV gives Career Adviser the career context it needs. Job Search remains separate and is checked against its own readiness requirements.</p><Link to="/profile/cv">Confirm your CV</Link></section></main>;
  const journey = onboarding.adviser.journey;
  const current = clarifications.find((item) => item.clarification_id === active) ?? clarifications.find((item) => item.status === "review_ready") ?? clarifications[0];
  const canConfirm = current?.status === "review_ready" && answer === interpretedAnswer && !locked;
  const pendingMessage = pending === "save" ? intakeRefreshPending ? "Refreshing career context…" : "Saving your career direction…" : pending === "assessment" ? "Preparing your career assessment…" : pending === "confirm-assessment" ? "Saving your assessment decision…" : pending === "interpret" ? "Reviewing your answer…" : pending === "confirm-clarification" ? "Saving your confirmation…" : "";
  const focusIntake = () => document.getElementById("career-direction")?.focus();
  const focusEnrichment = () => document.getElementById("profile-suggestions-heading")?.focus();
  const nextAction = dirty ? "save_intake" : assessment?.status === "review_ready" ? "review_assessment" : assessment?.status === "confirmed" && current?.status === "review_ready" ? "confirm_clarification" : assessment?.status === "confirmed" && current && current.status !== "confirmed" ? "answer_follow_up" : confirmedTransition ? (journey.unresolved_profile_enrichment_count > 0 ? "review_profile_enrichment" : "update_assessment") : assessment?.status === "stale" ? "update_assessment" : assessment === null && saved === null ? "start_intake" : assessment === null && saved ? "create_assessment" : journey.next_action;
  const journeyMessage = error === "Adviser status is unavailable."
    ? "Career Adviser status could not be refreshed. Retry before continuing."
    : journey.status_category === "up_to_date" ? "Career Adviser is up to date. Confirmed guidance can add context to opportunity evaluation."
      : journey.status_category === "review" ? "Your new career information is ready for your review."
        : journey.status_category === "update" ? "You added new information. Your assessment can now be improved."
          : "Career Adviser is an optional way to explore your career direction and strengthen job-search context.";
  const actionLabel: Record<string, string> = {
    save_intake: "Save changes", complete_profile: "Confirm your CV", start_intake: "Tell Career Adviser what you’re looking for", answer_follow_up: "Continue with this follow-up",
    create_assessment: "Create my career assessment", review_assessment: "Review and confirm this assessment",
    confirm_clarification: "Yes, that’s right", review_profile_enrichment: "Review for Profile",
    update_assessment: "Update my assessment", find_jobs: journey.job_search_ready ? "Find jobs" : "Check Profile readiness",
  };
  const doNextAction = () => {
    if (nextAction === "save_intake") void save();
    else if (nextAction === "start_intake") focusIntake();
    else if (nextAction === "review_assessment") void confirmAssessment();
    else if (nextAction === "confirm_clarification") void confirmClarification();
    else if (nextAction === "answer_follow_up") answerRef.current?.focus();
    else if (nextAction === "review_profile_enrichment") focusEnrichment();
    else if (nextAction === "create_assessment" || nextAction === "update_assessment") void mutateAssessment();
    else if (nextAction === "complete_profile") navigate("/profile/cv");
    else if (nextAction === "find_jobs") navigate(journey.job_search_ready ? "/jobs" : "/profile/cv");
  };
  return <main className="workspace adviser-page">
    {pendingMessage && <p role="status">{pendingMessage}</p>}{error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}
    {saved === undefined ? <section className="card"><h1>Career Adviser</h1><p className="muted" role="status">Loading your saved career direction…</p><button onClick={() => void load()}>Retry</button></section> : <>
      <section className="card adviser-journey" aria-labelledby="adviser-journey-heading">
        <p className="eyebrow">Your career journey</p><h1 id="adviser-journey-heading">Career Adviser</h1>
        <p>{journeyMessage}</p>{error === "Adviser status is unavailable." && <button type="button" className="button-secondary" onClick={() => void load()}>Refresh Career Adviser</button>}
        {dirty && <p className="notice" role="status">You have unsaved changes. Save or discard them before continuing to assessment, clarification, or Profile review.</p>}
        {!dirty && journey.unresolved_profile_enrichment_count > 0 && <p className="muted">There {journey.unresolved_profile_enrichment_count === 1 ? "is 1 optional Profile update" : `are ${journey.unresolved_profile_enrichment_count} optional Profile updates`} to review. You can do this now or continue to your assessment.</p>}
        {assessment !== undefined && <button type="button" disabled={Boolean(pending) || saved === undefined || (nextAction === "review_assessment" && locked) || (nextAction === "confirm_clarification" && !canConfirm)} onClick={doNextAction}>{actionLabel[nextAction] ?? "Continue"}</button>}
        {assessment?.status === "confirmed" && journey.current_follow_up_available && <button type="button" className="button-secondary" onClick={() => { setFollowUpDismissed(false); answerRef.current?.focus(); }}>Answer an optional follow-up</button>}
        <p className="muted">Career Adviser is optional. <Link to="/jobs">Job Search</Link> remains available whenever your Profile meets its own readiness checks.</p>
      </section>
      <section className="card adviser-intake" aria-labelledby="adviser-intake-heading">
        <h2 id="adviser-intake-heading">Your career direction</h2><p className="muted">A few notes about what you want help with. You can update these at any time.</p>
        <label htmlFor="career-direction">Where would you like your career to go?<textarea id="career-direction" value={form.career_direction} disabled={Boolean(pending)} onChange={(event) => setForm({ ...form, career_direction: event.target.value })} /></label>
        <section aria-labelledby="what-matters-heading"><h3 id="what-matters-heading">What matters to you</h3><p className="muted">Share your preferences, motivations, strengths, and trade-offs in your next role.</p>{(["work_preferences", "motivations", "self_assessment", "tradeoffs"] as const).map((key) => <ListInput key={key} label={({ work_preferences: "What do you want in your next role?", motivations: "What motivates you?", self_assessment: "What are your strengths or areas to build?", tradeoffs: "What trade-offs matter most?" })[key]} values={form[key]} disabled={Boolean(pending)} onChange={(next) => setForm({ ...form, [key]: next })} />)}</section>
        <section aria-labelledby="practical-requirements-heading"><h3 id="practical-requirements-heading">Practical requirements</h3><p className="muted">Add any constraints or eligibility details that should shape your options.</p><ListInput label="What should we account for?" values={form.constraints} disabled={Boolean(pending)} onChange={(next) => setForm({ ...form, constraints: next })} />{eligibilityLists.map((key) => <ListInput key={key} label={({ work_authorisation: "Where can you work?", security_clearances: "Any required clearances?", locations: "Which locations work for you?" })[key]} values={form.eligibility[key]} disabled={Boolean(pending)} onChange={(next) => setForm({ ...form, eligibility: { ...form.eligibility, [key]: next } })} />)}</section>
        <div className="cv-actions"><button type="button" className="button-secondary" disabled={Boolean(pending)} onClick={() => void save()}>{pending === "save" ? "Saving…" : "Save career direction"}</button>{dirty && <button type="button" className="button-secondary" disabled={Boolean(pending)} onClick={() => setForm(saved ?? blank())}>Discard changes</button>}</div>
      </section>
      {assessment === undefined && <section className="card"><p className="muted" role="status">Loading your career assessment…</p><button className="button-secondary" onClick={() => void load()}>Retry</button></section>}
      {assessment && <AssessmentView assessment={assessment} />}
      {assessment?.status === "review_ready" && <section className="card"><h2>Review your assessment</h2><p>This is a draft. Confirm it before Career-trans uses its role directions and search strategy to add context to opportunity evaluation.</p><button type="button" className="button-secondary" disabled={locked} onClick={() => void mutateAssessment()}>Create a different assessment</button></section>}
      {assessment?.status === "confirmed" && <section className="card"><h2>Optional follow-up</h2><p className="muted">Confirmed guidance is active. Answering a follow-up is optional and updates this assessment cycle.</p>{clarificationAuthority === "loading" && <p className="muted" role="status">Loading an optional follow-up…</p>}{clarificationAuthority === "unavailable" && <><p role="alert">{clarificationError}</p><button className="button-secondary" onClick={() => void loadClarifications()}>Retry follow-up</button></>}{clarificationAuthority === "ready" && (!current || followUpDismissed) && <p>No optional follow-up is available right now.</p>}{clarificationAuthority === "ready" && current && !followUpDismissed && <section className="clarification-card" aria-label="Current optional follow-up"><p className="muted">One thing I’d like to understand better</p><p>{current.question_text}</p><label htmlFor="clarification-answer">Your answer</label><textarea ref={answerRef} id="clarification-answer" value={answer} onChange={(event) => setAnswer(event.target.value)} disabled={locked} />{current.interpretation && <article className="evidence-card"><h3>Here’s what I understood</h3><p>{current.interpretation.confirmed_context_summary}</p>{answer !== interpretedAnswer && <p className="notice">You changed your answer. Review it again before confirming.</p>}</article>}<div className="cv-actions">{(current.status !== "review_ready" || answer !== interpretedAnswer) && <button type="button" className="button-secondary" disabled={locked || !answer.trim()} onClick={() => void interpret()}>Review my answer</button>}<button type="button" className="button-secondary" disabled={Boolean(pending)} onClick={() => setFollowUpDismissed(true)}>Do this later</button></div></section>}</section>}
      {confirmedTransition && <section className="card" aria-live="polite"><h2>Your new career information is ready for your review.</h2><p>{confirmedTransition.question_text}</p>{confirmedTransition.answer_text && <p>{confirmedTransition.answer_text}</p>}{confirmedTransition.interpretation && <p>{confirmedTransition.interpretation.confirmed_context_summary}</p>}<p className="muted">Your assessment now has new information available for an update. You can review optional Profile changes before updating it.</p></section>}
      <ProfileSuggestions api={api} confirmedClarification={confirmedTransition} enrichment={journey.next_enrichment as Enrichment} activeProfileDraft={journey.active_profile_draft} onResolved={() => { void refreshDependentAuthority(); }} />
    </>}
  </main>;
}
