import { FormEvent, useEffect, useState } from "react";
import { Navigate, Route, Routes, useNavigate } from "react-router-dom";
import { type OnboardingStatus, type Profile } from "./api";
import { ApiError, useAuth } from "./auth";

function Protected({ children }: { children: React.ReactNode }) { const { status, retryRestore } = useAuth(); return status === "checking" ? <p>Checking your session…</p> : status === "unavailable" ? <p>Session validation is temporarily unavailable. <button onClick={retryRestore}>Retry</button></p> : status === "authenticated" ? <>{children}</> : <Navigate to="/login" replace />; }
function Login() { const { login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await login(String(data.get("email")), String(data.get("password"))); navigate("/"); } catch (e) { setError(e instanceof ApiError && e.status === 401 ? "Incorrect email or password." : "Login is unavailable."); } } return <form onSubmit={submit}><h1>Sign in</h1><input name="email" type="email" required /><input name="password" type="password" required /><button>Sign in</button>{error && <p role="alert">{error}</p>}</form>; }
function Register() { const { register } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await register(String(data.get("email")), String(data.get("password"))); navigate("/login"); } catch (e) { setError(e instanceof ApiError && e.status === 409 ? "An account already exists for this email." : "Registration is unavailable."); } } return <form onSubmit={submit}><h1>Create account</h1><input name="email" type="email" required /><input name="password" type="password" required /><button>Create account</button>{error && <p role="alert">{error}</p>}</form>; }
const fields = ["display_name", "headline", "current_role", "location", "summary", "career_goal", "job_search_criteria", "preferred_email", "phone", "linkedin_url", "github_url", "portfolio_url"] as const;
type Values = Record<(typeof fields)[number], string>;
const emptyValues = (): Values => Object.fromEntries(fields.map((field) => [field, ""])) as Values;
export function ProfileForm({ profile, onSaved }: { profile: Profile | null; onSaved: () => void }) { const { api } = useAuth(); const [error, setError] = useState(""); const [values, setValues] = useState<Values>(emptyValues); useEffect(() => setValues(Object.fromEntries(fields.map((field) => [field, profile?.[field] ?? ""])) as Values), [profile]); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); try { await api.request("/api/v1/profile", { method: profile ? "PATCH" : "POST", body: JSON.stringify(values) }); onSaved(); } catch { setError("Profile could not be saved."); } } return <form onSubmit={submit}><h2>{profile ? "Edit profile" : "Create profile"}</h2>{fields.map((field) => <label key={field}>{field.replaceAll("_", " ")}<input name={field} value={values[field]} onChange={(event) => setValues({ ...values, [field]: event.target.value })} /></label>)}<button>Save profile</button>{error && <p role="alert">{error}</p>}</form>; }
function Home() { const { api, logout, user } = useAuth(); const [status, setStatus] = useState<OnboardingStatus | null>(null); const [profile, setProfile] = useState<Profile | null | undefined>(undefined); const [error, setError] = useState(""); const load = async () => { try { const [onboarding, existing] = await Promise.all([api.request<OnboardingStatus>("/api/v1/onboarding/status"), api.request<Profile>("/api/v1/profile").catch((e) => e instanceof ApiError && e.status === 404 ? null : Promise.reject(e))]); setStatus(onboarding); setProfile(existing); } catch { setError("Your onboarding status is unavailable."); } }; useEffect(() => { void load(); }, []); return <main><button onClick={logout}>Sign out</button><h1>Welcome {user?.email}</h1>{error && <p role="alert">{error}</p>}<ol><li>✓ Account</li><li>{status?.profile_exists ? "✓ Profile saved" : "○ Profile"}</li><li aria-disabled="true">○ CV — Coming in the next UI slice</li><li aria-disabled="true">○ Career Adviser — Available after confirmed CV</li></ol>{status?.candidate_context_ready && status.latest_cv_draft?.state === "review_ready" && <p>Active candidate profile ready; newer CV update awaiting review.</p>}{profile === undefined ? <p>Loading profile…</p> : <ProfileForm profile={profile} onSaved={load} />}</main>; }
export function App() { return <Routes><Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} /><Route path="/" element={<Protected><Home /></Protected>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
